/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lsm.tree;


interface MemTableIface {
    public <K, V> MemTableAddStatus  add(byte[] key, byte[] value);
    public <K> MemTableDeleteStatus  delete(byte[] key);

    public <K> MemTableFindStatus  find(byte[] key);

}



public class App {

    // task(001)
    public static String DataDir = "/path/to/dataDir";

    public static void main(String[] args) {
        // 1. create store config
        StoreConfig config = new StoreConfig(DataDir);
        System.out.println(String.format("Initializing db lib with config: [%s]", config));

        // 2. create connection

        // the db will eventually be exposed from a library.
        // a library is passive; the requests would come from the application
        // invoking the library, which we'll call "the client"
        // drawing inspiration from sqlite, the methods invoked would be
        // open -> opens a connection to db
        // exec -> execute a statement; perhaps more simply add(key, value), del(key, value), get(key), list
        // close -> close a connection and persist state

        // for now, we have one massive storage data structure;
        // user/app can achieve logical separation by encoding the key like: tree_0.key_0
        // later we can add ability to create separate data structures, comparable to new tree or tables
        Connection conn = new Connection(config);

        // todo: create an emulate_work(conn), that performs various, add, del, get, list ops on db


    }
}
